[plugin]
id = "crypto-compiler-plugin"
class = "io.ballerina.stdlib.crypto.compiler.CryptoCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/crypto-compiler-plugin-2.9.1-SNAPSHOT.jar"
